### PR TITLE
RFC 84: Replace Static by a gem

### PR DESCRIPTION
**Pull request by tijmenb**
👉 [Rendered version](https://github.com/alphagov/govuk-rfcs/blob/bc8ffe85cdf5cdf5005502cba50d5b64237f1b71/rfc-084-frontend-in-a-gem.md)

### CODE REVIEW

**Comment by h-lame** [comment]
One of the things we have to do a lot in the surveys and support team is deliver surveys that run across multiple pages and frontends on GOV.UK.  This is currently a JS file delivered as a shared asset by static which makes the process easy as it's used by every frontend.  We don't need to know which frontend will render a given page; we only need to make the change in one place and deploy one app to affect the entire site.  This is also something we do a lot, we probably do at least one survey related change (adding surveys, extending surveys, tweaking frequencies, etc...) most weeks.

The workflow for surveys is is a fairly minor consideration in the grand scheme of things, but it would be great if this rfc accommodated that workflow somehow.  Do we imagine keeping any mechanism for shared assets that can be used across all apps without doing an update and release dance on a gem + all the frontend apps?

**Comment by tijmenb** [comment]
@h-lame That's a good point. This also applies to the emergency banner, which we haven't considered in this proposal. We'll have to come up with something for that.

**Comment by nickcolley** [comment]
Can we reduce the scope of this RFC to things that change most often? If we reduced the scope to the components first it might be easier to push this forwards?

**Comment by tijmenb** [comment]
Maybe something like static should stay around, but for very limited purposes. How about each frontend app has both a global & local bundle. A layout would look like:

```erb
<% if Rails.env.production? %>
  <%= javascript_include_tag "https://assets.publishing.service.gov.uk/survey.js" %>
  <%= stylesheet_link_tag "https://assets.publishing.service.gov.uk/survey.css" %>
  <%= javascript_include_tag "https://assets.publishing.service.gov.uk/jquery-and-such-3.2.1.js" %>
  <%= stylesheet_link_tag "https://assets.publishing.service.gov.uk/font-1.2.3.css" %>
<% else %>
  <%= javascript_include_tag "jquery-and-such-3.2.1.js" %>
  <%= stylesheet_link_tag "font-1.2.3.css" %>
<% end %>

<%= javascript_include_tag "application.js" %>
<%= stylesheet_link_tag "application.css" %>
```

This would allow us to keep using the survey as we do currently and solves a large part of the problem with bundle size.

**Comment by nickcolley** [comment]
I feel really uncomfortable giving a 👍  to any approach that does not remove as much duplication as possible, if it's hard we should go the extra mile because it'll impact our users for our own gain.

**Comment by fofr** [comment]
Following on from Nick's point, we have a story for looking at moving components from static to the govuk_publishing_components gem:
https://trello.com/c/q7x0jvzK/62-make-govukpublishingcomponents-the-home-of-components-shared-between-apps

> Put a single component in govuk_publishing_components so that it can be shared between apps. A good starting point would be the lead paragraph component.
>
> Components can already be shared using static but this has risks:
>
> * changes must be backwards compatible
> * caching layers mean that old HTML must be compatible with new CSS (https://github.com/alphagov/static/issues/1121)
> * component helpers can't easily be shared from static, leading to more logic in the view
> * components can't be easily iterated when they live in static

Even with this approach, we use the analytics component to role out small analytics tweaks across all apps, much like the survey changes. That said, this template is a good example of the limits of components without helpers in static:

https://github.com/alphagov/static/blob/master/app/views/govuk_component/analytics_meta_tags.raw.html.erb

**Comment by andysellick** [comment]
Just to record a bit of technical debt... we've built a new component called a task list, which is designed to both sit on its own page in Collections but also in the sidebar of a wide variety of pages across GOV.UK. It was originally going to be a variation on the accordion component but due to this overall problem we decided to keep the accordion in Collections as is and copy and modify the code to a new task list component in static.

Although the task list component has considerable changes from the accordion, the basic expand/collapse functionality is common code that could be built and then reused in both components. The outcome of the task list work is still ongoing and further iterations of the component are possible but still worth recording here for future reference. PR for the component is here: https://github.com/alphagov/static/pull/1173

**Comment by rubenarakelyan** [comment]
How about having new HTML/CSS/JS deployed to asset-manager as versioned files and then having a "slimmer/static"-equivalent gem for each app that points to a specific version of the files? Then you can have different apps with different gem versions that point at different versions of assets but you don't have to co-ordinate breaking changes across multiple frontend apps - their gem versions can be upgraded one-by-one. Apps that share the same gem version will point at the same files which will then be cached by browsers.

**Comment by cbaines** [comment]
> Just to record a bit of technical debt... we've built a new component called a task list, which is designed to both sit on its own page in Collections but also in the sidebar of a wide variety of pages across GOV.UK. It was originally going to be a variation on the accordion component but due to this overall problem we decided to keep the accordion in Collections as is and copy and modify the code to a new task list component in static.

It would be good to know what specific issues the new task list component is running in to? I'm interested in understanding where the caching issues are coming from, as looking at [1], as far as I can see, the requested assets look to be content addressed, as the paths contain hashes.

1: https://www.gov.uk/learn-to-drive-a-car

**Comment by andysellick** [comment]
> It would be good to know what specific issues the new task list component is running in to? I'm interested in understanding where the caching issues are coming from, as looking at [1], as far as I can see, the requested assets look to be content addressed, as the paths contain hashes.

Reuse of code is poor - the task list component has much code in common with the accordion component but they can't share it. In an ideal world we'd write a generic bit of accordion JS that could be used by both components. They also have similar GA tracking JS, which again could be reused rather than duplicated.

**Comment by h-lame** [comment]
I'd like to unpick the:

> but they can't share it.

and 

> In an ideal world we'd write a generic bit of accordion JS that could be used by both components

statements, because nothing about static prevents us writing that JS and hosting it in static and then having Collections re-use that for it's accordion, and static re-use it for the task-list component.  Or, more correctly, nothing in _my understanding_ of how things hangs together prevents it.  Obviously though, something _did_ prevent it, so maybe a quick win is to write down the exact problem and we can fix that as a stepping stone towards the goal of this RFC.

**Comment by andysellick** [comment]
It'll work in the browser but not in a test. A component JS test (in say, Collections) that relies upon JS in static can't currently access it. We can make up these gaps with smokey tests but they're not linked to PRs.

**Comment by h-lame** [comment]
Thanks @andysellick - that's a really good point - I hadn't considered testing where the static JS isn't available.  I guess we could set up integration tests in the app to rely on running a local copy of static, but that definitely feels hard to orchestrate and I'm not sure any other parts of gov.uk do anything similar (other than the e2e tests or smokey which as you rightly say, aren't ideal because they're not attached to PRs).

**Comment by cbaines** [comment]
> Thanks @andysellick - that's a really good point - I hadn't considered testing where the static JS isn't available. I guess we could set up integration tests in the app to rely on running a local copy of static, but that definitely feels hard to orchestrate and I'm not sure any other parts of gov.uk do anything similar (other than the e2e tests or smokey which as you rightly say, aren't ideal because they're not attached to PRs).

The tests for most applications already rely on services, e.g. the Publishing API relies on PostgreSQL.

You could deploy static to the ci-agents, like the other services used in tests?

**Comment by tijmenb** [comment]
> You could deploy static to the ci-agents, like the other services used in tests?

Yes, but this doesn't solve the other problems described in the RFC, so it would be a partial solution at best.

**Comment by nickcolley** [comment]
Sorry, I commented without reading, and closed this by mistake. Sorry all :)

**Comment by tijmenb** [comment]
Thanks everyone for the comments! I'm going to pause this RFC.

I think there's broad agreement. The main blockers to getting this RFC accepted are answers to the following questions:

- How do we deal with duplication of asset downloads?
- Do we completely retire static? What do we do with the survey, emergency publishing, fonts and layouts?

Follow up actions before re-opening:

- [ ] Determine the user impact of duplicated assets in different scenarios, so that we can understand how much effort to put into a solution
- [ ] Following on from that, spike a system that [shares assets for users](https://github.com/alphagov/govuk-rfcs/pull/84#issuecomment-342460714)
- [ ] Come up with a vision on emergency publishing in this system  
- [ ] Come up with a vision on surveys in this system  
- [ ] Come up with a vision on layouts in this system

**Pull request closed without merging**
